---
title: "Solución ejercicio: Proyectos de Ciencia de Datos"
date: "`r format(Sys.time(), '%B, %Y')`"
author: "DSLab"
mainfont: Roboto
fontsize: 12pt
output:
   pdf_document:
     latex_engine: xelatex
---

Por ejemplo, consideremos el siguiente caso de éxito:

**Detección del cáncer de mama metastásico**

1.  ¿Cuál es el problema que se trata de resolver? ¿Qué preguntas de negocio son las más importantes?

Las metástasis de un tumor influyen en las decisiones terapéuticas de diversos tipos de cáncer. La identificación histológica de las células tumorales en los ganglios linfáticos puede ser laboriosa y propensa a errores, especialmente en el caso de focos tumorales pequeños.

El objetivo es detectar cáncer de mama metastásico en biopsias de ganglio linfático centinela.

2.  ¿Cuál es el origen de los datos? Existían antes de plantear la pregunta o fueron resultado de una técnica de muestreo.

Para lleva a cabo el estudio, se obtuvieron imágenes de ganglios linfáticos teñidos con hematoxilina-eosina de 399 pacientes (conjunto de datos de desafío Camelyon16 que dominio público). 

3.  ¿Qué has podido averiguar sobre el proceso de obtención y preparación de los datos?

El algoritmo se desarrolló utilizando 270 muestras de entrenamiento y se evaluó en los 129 pacientes restantes. Además, se compararon los resultados con los obtenidos en un laboratorio independiente.

4.  ¿Qué técnicas de Aprendizaje Automático (Supervisado o no supervisado) han sido empleadas?

El algoritmo empleado es una red neuronal profunda, Deep Learning, denominada LYNA: "LYmph Node Assistant". Adjuntamos archivo con la descripción del algoritmo.

5.  ¿Cuál ha sido el rendimiento del modelo?

El modelo propuesto, LYNA presenta un "área bajo la curva" de 99% y una sensibilidad del 91%.

6.  ¿Has podido averiguar cómo se presentaron los datos al cliente?

Se presentan la metodología, el algoritmo y sus resultados en la revista científica *Archives of Pathology & Laboratory Medicne*.

7.  Finalmente, ¿se puso en producción el modelo resultante? ¿sigue funcionando?

Este suele ser un dato del que no se dispone, sin embargo parece ser que el modelo propuesto puede ser utilizado por diversas instituciones.

Referencias:

- https://meridian.allenpress.com/aplm/article/143/7/859/10038/Artificial-Intelligence-Based-Breast-Cancer-Nodal
- https://allen.silverchair-cdn.com/allen/content_public/journal/aplm/143/7/10.5858_arpa.2018-0147-oa/2/arpa_2018-0147-oa.pdf?Expires=1701888792&Signature=kYuABkfH35mSKkDqED9zmS32Tqum6TQV8E4aEJGU6lS1LLjx9oujKxgVFD4BS0ja6zV~mV3VVrKXQxG~jYSZPthRozu73hmaXTtxAk7C6TajthTCqB1mo~XTS1A5J~rM7u6OAObs3Upvhr4cwhyLIkcCHrhMhBWVQgVaKM3CESTumJzkAx6X3IvHh8hWR3LsTiOl1nswcCJ9ntg~LRsRBNq8tt5LQJSoR-bKVX2ASBhcU-vVpLtA9bjqQSc8oG7hDUtoby8oUsMN5XBKrXGqUf5Ss1iZwyxQ-YfbThJcDkeD9LKZtN1DV0TF-DIlXBowy4ib6ZwHh9OO34fG3yLC8Q__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA

